"use client";
import {useMemo,useState} from "react";
const initial={project_id:"",service_plan:"Monthly content management",month:"",currency:"AED",amount_due:"",amount_paid:"",payment_note:""};
const emptyExpense={project_id:"",spent_on:"",description:"",amount:"",currency:"AED",notes:""};
const money=(n,c="AED")=>new Intl.NumberFormat("en-AE",{style:"currency",currency:c,maximumFractionDigits:2}).format(Number(n)||0);
const dateMonth=()=>new Date(Date.now()+4*3600000).toISOString().slice(0,7);
export default function WorkspaceFinance({ws}){
 const {db,role,data,refresh}=ws;
 const [currency,setCurrency]=useState("AED"),[month,setMonth]=useState(dateMonth()),[type,setType]=useState("billing");
 const [formOpen,setFormOpen]=useState(false),[expenseOpen,setExpenseOpen]=useState(false),[currentId,setCurrentId]=useState(null);
 const [fields,setFields]=useState({...initial,month:dateMonth()}),[expense,setExpense]=useState({...emptyExpense,spent_on:dateMonth()+"-01"});
 const [busy,setBusy]=useState(false),[feedback,setFeedback]=useState("");
 const finance=data.finance||[],expenses=data.expenses||[];
 const projectName=id=>data.projects.find(p=>p.id===id)?.client_name||data.projects.find(p=>p.id===id)?.name||"Unassigned";
 const rows=useMemo(()=>finance.filter(x=>x.month?.slice(0,7)===month&&x.currency===currency).sort((a,b)=>projectName(a.project_id).localeCompare(projectName(b.project_id))),[finance,month,currency,data.projects]);
 const spent=useMemo(()=>expenses.filter(x=>x.spent_on?.slice(0,7)===month&&x.currency===currency),[expenses,month,currency]);
 const due=rows.reduce((a,r)=>a+Number(r.amount_due),0),received=rows.reduce((a,r)=>a+Number(r.amount_paid),0),costs=spent.reduce((a,r)=>a+Number(r.amount),0);
 function edit(row){setFields({project_id:row.project_id,service_plan:row.service_plan,month:row.month?.slice(0,7),amount_due:String(row.amount_due),amount_paid:String(row.amount_paid),currency:row.currency,payment_note:row.payment_note||""});setCurrentId(row.id);setFormOpen(true)}
 async function save(e){
  e.preventDefault();if(role!=="ceo")return;
  if(!fields.project_id||!fields.month||!fields.service_plan.trim()){setFeedback("Select a client project and complete the plan.");return}
  const amount_due=Number(fields.amount_due),amount_paid=Number(fields.amount_paid);
  if(!Number.isFinite(amount_due)||!Number.isFinite(amount_paid)||amount_due<0||amount_paid<0){setFeedback("Amounts must be zero or greater.");return}
  setBusy(true);setFeedback("");
  const payload={project_id:fields.project_id,service_plan:fields.service_plan.trim(),month:fields.month+"-01",currency:fields.currency,amount_due,amount_paid,payment_note:fields.payment_note.trim()};
  if(currentId)payload.id=currentId;
  const response=currentId?await db.from("adva_monthly_finances").update(payload).eq("id",currentId):await db.from("adva_monthly_finances").upsert(payload,{onConflict:"project_id,service_plan,month"});
  setBusy(false);
  if(response.error){setFeedback(response.error.message);return}
  setFeedback("Monthly plan saved. Changes are recorded in the finance audit history.");setFormOpen(false);setCurrentId(null);setFields({...initial,month:dateMonth()});refresh();
 }
 async function saveExpense(e){
  e.preventDefault();if(role!=="ceo")return;
  if(!expense.description.trim()||!expense.spent_on||!(Number(expense.amount)>=0)){setFeedback("Enter the expense details.");return}
  setBusy(true);setFeedback("");
  const {error}=await db.from("adva_expenses").insert({project_id:expense.project_id||null,spent_on:expense.spent_on,description:expense.description.trim(),amount:Number(expense.amount),currency:expense.currency,notes:expense.notes});
  setBusy(false);if(error){setFeedback(error.message);return}
  setFeedback("Expense recorded in the CEO ledger.");setExpenseOpen(false);setExpense({...emptyExpense,spent_on:dateMonth()+"-01"});refresh();
 }
 if(role!=="ceo")return <div className="aws-access-denied">Finance is restricted to the ADVA CEO.</div>;
 return <div className="aws-module aws-finance">
  <div className="aws-page-heading"><div><span className="aws-eyebrow"><i/> CEO ONLY / PRIVATE FINANCE</span><h1>Numbers, with clarity.</h1><p>Client plans, monthly payments, expenses and outstanding balances. Not visible to freelancers or clients.</p></div><div className="aws-page-heading-actions"><button className="aws-outline" onClick={()=>setExpenseOpen(true)}>+ Expense</button><button className="aws-primary aws-compact" onClick={()=>{setFields({...initial,project_id:data.projects[0]?.id||"",month});setCurrentId(null);setFormOpen(true)}}>+ Monthly plan</button></div></div>
  <div className="aws-toolbar"><label>BILLING MONTH<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><label>CURRENCY<select value={currency} onChange={e=>setCurrency(e.target.value)}>{["AED","USD","OMR","EUR","GBP"].map(c=><option key={c} value={c}>{c}</option>)}</select></label><div className="aws-inline-info">Amounts reflect manually entered records, not bank reconciliation.</div></div>
  {feedback&&<div role="status" className="aws-feedback">{feedback}<button onClick={()=>setFeedback("")}>×</button></div>}
  <div className="aws-finance-kpis"><article><span>AMOUNT TO RECEIVE</span><strong>{money(due,currency)}</strong><small>Planned client services</small></article><article><span>PAYMENTS RECORDED</span><strong>{money(received,currency)}</strong><small>CEO-entered receipts</small></article><article><span>OUTSTANDING</span><strong>{money(Math.max(0,due-received),currency)}</strong><small>{received>due?money(received-due,currency)+" recorded in credits":"Due minus received"}</small></article><article><span>EXPENSES RECORDED</span><strong>{money(costs,currency)}</strong><small>Monthly spend</small></article></div>
  <div className="aws-finance-sections"><button className={type==="billing"?"active":""} onClick={()=>setType("billing")}>Client plans & payments</button><button className={type==="expenses"?"active":""} onClick={()=>setType("expenses")}>Expenses</button></div>
  <div className="aws-panel"><div className="aws-panel-title"><div><span>ADVA / PRIVATE LEDGER</span><h2>{type==="billing"?"Monthly plans":"Recorded expenses"}</h2></div><span>{type==="billing"?rows.length:spent.length} ENTRIES</span></div>
  {type==="billing"?(rows.length?<div className="aws-scroll-table"><table><thead><tr><th>Client / project</th><th>Service plan</th><th>Due</th><th>Paid</th><th>Outstanding</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{projectName(r.project_id)}</strong></td><td>{r.service_plan}</td><td>{money(r.amount_due,r.currency)}</td><td>{money(r.amount_paid,r.currency)}</td><td className={Number(r.amount_due)>Number(r.amount_paid)?"aws-outstanding":""}>{money(Number(r.amount_due)-Number(r.amount_paid),r.currency)}</td><td><button type="button" onClick={()=>edit(r)}>Edit ↗</button></td></tr>)}</tbody></table></div>:<div className="aws-empty"><strong>No payment records for this month.</strong><p>Add a service plan with its amount due and amount received to start tracking.</p><button className="aws-outline" onClick={()=>{setCurrentId(null);setFields({...initial,project_id:data.projects[0]?.id||"",month});setFormOpen(true)}}>Add first plan ↗</button></div>):(spent.length?<div className="aws-scroll-table"><table><thead><tr><th>Date</th><th>Project</th><th>Description</th><th>Amount</th></tr></thead><tbody>{spent.map(r=><tr key={r.id}><td>{r.spent_on}</td><td>{r.project_id?projectName(r.project_id):"ADVA / General"}</td><td>{r.description}</td><td>{money(r.amount,r.currency)}</td></tr>)}</tbody></table></div>:<div className="aws-empty"><strong>Nothing recorded yet.</strong><p>Expenses you enter will stay private to the CEO.</p></div>))}
  </div>
  <p className="aws-small-note">Finance figures are based on manual entries, with a change audit for monthly plans. This is an internal ledger, not automated bank reconciliation, tax advice, or payment processing.</p>
  {formOpen&&<div className="aws-modal"><button className="aws-backdrop" aria-label="Close finance entry" onClick={()=>setFormOpen(false)}/><form className="aws-modal-card" onSubmit={save}><header><div><span>CEO / FINANCE</span><h2>{currentId?"Update payment record":"Add monthly plan"}</h2></div><button type="button" onClick={()=>setFormOpen(false)}>×</button></header><label>Client project<select required value={fields.project_id} onChange={e=>setFields({...fields,project_id:e.target.value})}><option value="">Select a client</option>{data.projects.map(p=><option key={p.id} value={p.id}>{p.client_name||p.name}</option>)}</select></label><label>Service plan<input required value={fields.service_plan} maxLength={160} onChange={e=>setFields({...fields,service_plan:e.target.value})} placeholder="Monthly content management"/></label><div className="aws-form-pair"><label>Billing month<input required type="month" value={fields.month} onChange={e=>setFields({...fields,month:e.target.value})}/></label><label>Currency<select value={fields.currency} onChange={e=>setFields({...fields,currency:e.target.value})}>{["AED","USD","OMR","EUR","GBP"].map(c=><option key={c} value={c}>{c}</option>)}</select></label></div><div className="aws-form-pair"><label>Amount to be paid<input min="0" step="0.01" type="number" required value={fields.amount_due} onChange={e=>setFields({...fields,amount_due:e.target.value})}/></label><label>Amount paid<input min="0" step="0.01" type="number" required value={fields.amount_paid} onChange={e=>setFields({...fields,amount_paid:e.target.value})}/></label></div><label>Internal payment note<textarea rows={2} maxLength={1000} value={fields.payment_note} onChange={e=>setFields({...fields,payment_note:e.target.value})} placeholder="Payment reference, follow-up, invoice number…"/></label><div className="aws-form-summary"><span>OUTSTANDING</span><strong>{money(Number(fields.amount_due)-Number(fields.amount_paid),fields.currency)}</strong></div><button disabled={busy} type="submit" className="aws-primary">{busy?"Saving…":"Save finance record"} ↗</button></form></div>}
  {expenseOpen&&<div className="aws-modal"><button className="aws-backdrop" aria-label="Close expense entry" onClick={()=>setExpenseOpen(false)}/><form className="aws-modal-card" onSubmit={saveExpense}><header><div><span>CEO / EXPENSE</span><h2>Record a cost</h2></div><button type="button" onClick={()=>setExpenseOpen(false)}>×</button></header><label>Expense description<input required minLength={2} maxLength={250} value={expense.description} onChange={e=>setExpense({...expense,description:e.target.value})} placeholder="Transport, equipment rental, freelance payment…"/></label><label>Project (optional)<select value={expense.project_id} onChange={e=>setExpense({...expense,project_id:e.target.value})}><option value="">ADVA general expense</option>{data.projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="aws-form-pair"><label>Date<input type="date" required value={expense.spent_on} onChange={e=>setExpense({...expense,spent_on:e.target.value})}/></label><label>Amount<input type="number" min="0" required step="0.01" value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value})}/></label></div><label>Currency<select value={expense.currency} onChange={e=>setExpense({...expense,currency:e.target.value})}>{["AED","USD","OMR","EUR","GBP"].map(c=><option key={c} value={c}>{c}</option>)}</select></label><label>Private notes<textarea maxLength={1000} rows={2} value={expense.notes} onChange={e=>setExpense({...expense,notes:e.target.value})}/></label><button type="submit" disabled={busy} className="aws-primary">Save expense ↗</button></form></div>}
 </div>;
}